### ISSUE TITLE
Feature request: single column directory view

### ISSUE THREAD

**Issue by shabahengam** [jacokoo/fff#2]
opening any directory make a new column and it's a little confusing(at least for me).can you add a setting to enable single column view?

**Comment by jacokoo** [comment]
Display multiple columns is good for jump mode.
Could you please tell me why it confuses you?

**Comment by shabahengam** [comment]
for example look at [this picture](https://0x0.st/zI3b.png).there is 6 column.
i just need one column and that column should show the current directory.
[lf](https://github.com/gokcehan/lf) is multi column too, but you can [config that](https://github.com/gokcehan/lf/wiki/Tips) to show one column

**Comment by jacokoo** [comment]
I've added the single column mode. You can try it by add `single-column-mode: true` to `config.yml`.
But I strongly recommend you to use multiple column mode.

**Comment by shabahengam** [comment]
thank you so much for adding this feature.
but i get this error when i try to open a directory.[**bookmark disabled**]
`panic: runtime error: index out of range [-1]
goroutine 35 [running]:
github.com/jacokoo/fff/ui.(*Column).Last(...)
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/column.go:126
github.com/jacokoo/fff/ui.init.0.func7(0x6f7d40, 0xc0000878c0)
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:179 +0x5aa
github.com/jacokoo/fff/ui.dispatch(...)
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:121
github.com/jacokoo/fff/ui.startEventLoop()
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:368 +0x175
created by github.com/jacokoo/fff/ui.Start
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/ui.go:133 +0x48`

and this error [**bookmark enabled**]
`panic: interface conversion: ui.Drawer is *ui.Bookmark, not *ui.FileList`
`goroutine 19 [running]:
github.com/jacokoo/fff/ui.init.0.func7(0x6f7d40, 0xc0000858c0)
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:179 +0x5a5
github.com/jacokoo/fff/ui.dispatch(...)
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:121
github.com/jacokoo/fff/ui.startEventLoop()
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/event.go:368 +0x175
created by github.com/jacokoo/fff/ui.Start
/home/shabahengam/go/src/github.com/jacokoo/fff/ui/ui.go:133 +0x48`
