### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by zQueal** [jacokoo/fff#3]
```bash
❯ fff ~/Downloads
panic: CreateFile \C:\Users\zqueal\Downloads: The filename, directory name, or volume label syntax is incorrect.

goroutine 1 [running]:
github.com/jacokoo/fff/model.NewWorkspace(0x4, {0xc0000101e0, 0x19}, {0xc000010300, 0x1b})
        C:/Users/zqueal/Downloads/fff/model/workspace.go:24 +0x216
main.main()
        C:/Users/zqueal/Downloads/fff/main.go:129 +0xf2
Exception: fff exited with 2
[tty 52], line 1: fff ~/Downloads
```

**Comment by zQueal** [comment]
Any chance at all of this being worked at? Looks like `main.go` prepends `\` to windows paths maybe?
